version: '3.9' 

services:
  php-env:
    build: ../../docker #path to dockerfile
    volumes: 
      - ./src:/var/www/html
      - ./app/config/custom.php.ini:/usr/local/etc/php/custom.d
    ports:
      - 8082:80

  
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8083:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./app/config/php.ini:/usr/local/etc/php/php.ini